module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-background": "var(--app-background)",
        "app-primary": "var(--app-primary)",
        "black-color": "var(--black-color)",
        "color-dark-yellow": "var(--color-dark-yellow)",
        "color-light-green": "var(--color-light-green)",
        "color-tokenstext-color-1": "var(--color-tokenstext-color-1)",
        "gray-400": "var(--gray-400)",
        "gray-600": "var(--gray-600)",
        grey: "var(--grey)",
        "label-dark-primary": "var(--label-dark-primary)",
        "label-dark-tertiary": "var(--label-dark-tertiary)",
        "label-light-primary": "var(--label-light-primary)",
        "light-grey": "var(--light-grey)",
        outlines: "var(--outlines)",
        "system-bg-dark-base-primary": "var(--system-bg-dark-base-primary)",
        "systemgreen-light": "var(--systemgreen-light)",
        "text-color": "var(--text-color)",
        "white-color": "var(--white-color)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-bold": "var(--body-bold-font-family)",
        "body-medium": "var(--body-medium-font-family)",
        "body-regular": "var(--body-regular-font-family)",
        "body-semibold": "var(--body-semibold-font-family)",
        h1: "var(--h1-font-family)",
        h2: "var(--h2-font-family)",
        "small-body-bold": "var(--small-body-bold-font-family)",
        "small-body-medium": "var(--small-body-medium-font-family)",
        "small-body-regular": "var(--small-body-regular-font-family)",
        "small-body-semibold": "var(--small-body-semibold-font-family)",
        "text-sm-regular": "var(--text-sm-regular-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
